language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "sudo make sqlite3 deploy"
#  - "pip install -r imagedownloader/requirements.txt"
# # command to run tests
script: "sudo make test"
#nosetests
