language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "make sqlite3 deploy-withoutpip"
#  - "pip install -r imagedownloader/requirements.txt"
# # command to run tests
script: "make test"
#nosetests
after_success:
  - "coveralls"
