language: python
python:
  - "2.7"
# command to install dependencies
install:
  - "make sqlite3 deploy-withoutpip"
# command to run tests
script: "make test-coverage" #nosetests
after_success:
  - "coveralls"
