language: python
python:
  - "2.7.5"
# command to install dependencies
install:
  - "sudo make deploy"
  - "pip install -r imagedownloader/requirements.txt"
# # command to run tests
script: "python imagedownloader/manage.py test stations"
#nosetests
